Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
30

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
30
120

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
30
8

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
30
8

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
welcome
30
8

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 33, in <module>
    c = SciCalc('Salar')
TypeError: Calc.__init__() takes 1 positional argument but 2 were given

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 33, in <module>
    c = SciCalc('Salar')
TypeError: Calc.__init__() takes 1 positional argument but 2 were given

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
welcome Salar
30
8

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
in a

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 55, in <module>
    z.do()
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 48, in do
    pfint('in c')
NameError: name 'pfint' is not defined. Did you mean: 'print'?

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 55, in <module>
    z.do()
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 48, in do
    pfint('in c')
NameError: name 'pfint' is not defined. Did you mean: 'print'?

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
in a

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
in a
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.A'>, <class '__main__.C'>, <class 'object'>]

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Salar

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 78, in <module>
    ul.withdraw(200)
NameError: name 'ul' is not defined. Did you mean: 'u1'?

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
your current balance ist : 300

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
your current balance ist : -200

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : -200

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : 500

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : 500
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 91, in <module>
    u1.show_Details()
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 80, in show_Details
    print(self.name)
AttributeError: 'Bank' object has no attribute 'name'
>>> 
=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : 500
 name : Salar
age : 22
gender : male
>>> 
=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
Traceback (most recent call last):
  File "C:/Users/faten2/OneDrive/Desktop/oop-exercise.py", line 90, in <module>
    u1 = Bank('Salar' , 22, 'male')
TypeError: Bank() takes no arguments

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : 500
 name : Salar
age : 22
gender : male

=========== RESTART: C:/Users/faten2/OneDrive/Desktop/oop-exercise.py ==========
 welcome Salar
your current balance ist : 500
you dont have enough balance
your current balance ist : 500
 name : Salar
age : 22
gender : male
 welcome Issa
your current balance ist : 5000
your current balance ist : 5000
 name : Issa
age : 27
gender : male
